version: '3.8'

services:
  # PagePilot Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=file:/app/data/prod.db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=3000
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data:rw
      - ./logs:/app/logs:rw
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Optional: SQLite Web UI for database management
  sqlite-web:
    image: coleifer/sqlite-web
    restart: unless-stopped
    environment:
      - SQLITE_DATABASE=/data/prod.db
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/data:ro
    depends_on:
      - api
    command: ["sqlite_web", "/data/prod.db", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  sqlite_data:
    driver: local

networks:
  default:
    name: pagepilot-network 